version = 0.1
[pulpfree]
[pulpfree.deploy]
[pulpfree.deploy.parameters]
stack_name = "contact-api"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-188xbw0p20kz4"
s3_prefix = "contact-api"
region = "ca-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
