AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  contact-api
  
  SAM Template for contact-api

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5

Resources:
  ApiCertificate: # this will require logging into the certificate manager and clicking 'Create Records in Route53'
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: contact-api.webbtech.io
      ValidationMethod: DNS

  RestApi:
    Type: AWS::Serverless::Api
    DeletionPolicy: Delete
    DependsOn: ContactAPIFunction
    Properties:
      StageName: Prod
      # docs
      Domain:
        DomainName: contact-api.webbtech.io
        CertificateArn: !Ref ApiCertificate
        Route53:
          HostedZoneId: Z2TKD92HOCUXB7
          DistributionDomainName:
            Value: !Sub "https://${RestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"


  ContactAPIFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello-world/
      Handler: hello-world
      Runtime: go1.x
      Architectures:
        - x86_64
      Tracing: Active # https://docs.aws.amazon.com/lambda/latest/dg/lambda-x-ray.html
      Events:
        CatchAll:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: GET
            RestApiId: !Ref RestApi
        Ping:
          Type: Api
          Properties:
            Path: /ping
            Method: GET
            RestApiId: !Ref RestApi
        Err:
          Type: Api
          Properties:
            Path: /error
            Method: GET
            RestApiId: !Ref RestApi
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          PARAM1: VALUE

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  ApiId:
    Description: API ID
    Value:
      Ref: RestApi
  ApiURL:
    Description: "API Url"
    Value: !Sub "https://contact-api.webbtech.io/hello"
  ContactAPI:
    Description: "API Gateway endpoint URL for Prod environment for First Function"
    Value: !Sub "https://${RestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  ContactAPIFunction:
    Description: "First Lambda Function ARN"
    Value: !GetAtt ContactAPIFunction.Arn
  ContactAPIFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt ContactAPIFunctionRole.Arn
