AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'contact-api

  SAM Template for contact-api

  '
Globals:
  Function:
    Timeout: 5
Parameters:
  ParamMailRecipient:
    Description: Required. Mail recipient address
    Type: String
  ParamMailSender:
    Description: Required. Mail sender address
    Type: String
Resources:
  ApiCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: contact-api.webbtech.io
      ValidationMethod: DNS
  RestApi:
    Type: AWS::Serverless::Api
    DeletionPolicy: Delete
    DependsOn: ContactAPIFunction
    Properties:
      StageName: Prod
      Tags:
        BillTo: Webbtech
      GatewayResponses:
        UNAUTHORIZED:
          StatusCode: 401
          ResponseTemplates:
            application/json: '{ "message": $context.error.messageString }'
          ResponseParameters:
            Headers:
              Access-Control-Expose-Headers: '''WWW-Authenticate'''
              Access-Control-Allow-Origin: '''*'''
              Access-Control-Allow-Headers: '''*'''
      Domain:
        DomainName: contact-api.webbtech.io
        CertificateArn:
          Ref: ApiCertificate
        Route53:
          HostedZoneId: Z2TKD92HOCUXB7
          DistributionDomainName:
            Value:
              Fn::Sub: https://${RestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/
  ContactAPIFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ContactAPIFunction
      Handler: contact
      Runtime: go1.x
      Architectures:
      - x86_64
      Tracing: Active
      Policies:
      - AmazonDynamoDBFullAccess
      - AmazonSESFullAccess
      Events:
        Contact:
          Type: Api
          Properties:
            Path: /contact
            Method: POST
            RestApiId:
              Ref: RestApi
        Ping:
          Type: Api
          Properties:
            Path: /
            Method: GET
            RestApiId:
              Ref: RestApi
      Environment:
        Variables:
          RecipientEmail:
            Ref: ParamMailRecipient
          SenderEmail:
            Ref: ParamMailSender
          Stage: production
      Tags:
        BillTo: Webbtech
Outputs:
  ApiId:
    Description: API ID
    Value:
      Ref: RestApi
  ApiURL:
    Description: API Url
    Value:
      Fn::Sub: https://contact-api.webbtech.io/
  ContactAPI:
    Description: API Gateway endpoint URL for Prod environment for First Function
    Value:
      Fn::Sub: https://${RestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/
  ContactAPIFunction:
    Description: First Lambda Function ARN
    Value:
      Fn::GetAtt:
      - ContactAPIFunction
      - Arn
  ContactAPIFunctionIamRole:
    Description: Implicit IAM Role created for Hello World function
    Value:
      Fn::GetAtt:
      - ContactAPIFunctionRole
      - Arn
